### ISSUE TITLE
erro when Update firewall policy, object and etc...

### ISSUE THREAD

**Issue by rcedros** [jsimpso/PyFortiAPI#7]
I have a error when a tried update some firewall policy or object address:
      payload = {'subnet': '10.0.0.1 255.0.0.0'}
      device.update_firewall_address('obj11', payload)
      ERROR:root:Requested address "obj11" does not exist in Firewall config.
      404

The same happens when I chance firewall policy:
    ERROR:root:Requested Policy ID 4 does not exist in Firewall Config

Do you know about this problem?

Thanks

**Comment by rcedros** [comment]
I found the problem!

Even I used vdom="LAB" in login and my use is in the Global vdom, I can't update policy or object. But if my user is local and my user is especific to LAB vdom it works.

I think that is a bug, because I get create and delete, but update is not possible.

Thanks,

**Comment by k4mil666** [comment]
in my opinion, there is a missing "?vdom="+self.vdom in object_url in the function does_exist

is
request = session.get(object_url)

should be
request = session.get(object_url + "?vdom="+self.vdom)

and it work for me

**Comment by jsimpso** [comment]
Fixed by merging #10
